msyql:
  host: 127.0.0.1
  port: 3306
  db: qing
  user: root
  password: Mysql&8023yuan
  log_level: dev

logger:
  level: info
  prefix: '[qing]'
  director: log
  show_line: true
  log_in_console: true

system:
  host: "0.0.0.0"
  post: 8888
  env: dev
